### PR TITLE
Make it work with included files

### PR DESCRIPTION
**Pull request by wmertens**
My webpack config imports a few things and that seems to trigger the self-loading weirdness; with this patch everything works.

### CODE REVIEW

**Comment by wmertens** [comment]
The failing tests are due to it ignoring conditions the tests test :) No time to amend the tests right now though, sorry.

**Comment by adriantoine** [comment]
Hi @wmertens, thanks for your contribution! It makes sense but you need to fix the current failing test, which shouldn't be too hard I think, and also, can you please provide a test for that special case you've added?

Thanks! 😊

**Comment by wmertens** [comment]
@adriantoine done :)

**Comment by adriantoine** [comment]
Tests are still not passing due to an eslint error, can you add an `eslint` ignore there? Thanks!

**Comment by wmertens** [comment]
Hmm odd, the coverage is saying that the `return;` is not being tested, but isn't that exactly what the added test does? Any ideas?

**Comment by adriantoine** [comment]
Hi @wmertens, sorry I was busy, I'm having a look now

**Comment by adriantoine** [comment]
@wmertens I think there's a typo, your config file is called `empty-object.js` but in the test you're loading `empty-object.config.js`, I suggest you rename `empty-object.js` to `empty-object.config.js`.

**Comment by wmertens** [comment]
Good catch! I updated it.

>

**Comment by adriantoine** [comment]
Cool, thanks! It seems to have fixed the PR validation, not sure why we have several AppVeyor ones 🤔

**Comment by adriantoine** [comment]
@wmertens Your fix is included in `v2.1.2`, thanks for your contribution! 🎉

**Pull request merged**
